### ISSUE TITLE
need to updated: extends TextView Should change to AppCompatAutoCompleteTextView

### ISSUE THREAD

**Issue by geekxingyun** [RuffianZhong/RTextView#10]
感谢楼主分享，完美解决了我的问题。
不过有一点还是需要说明下
`public class RTextView extends AppCompatAutoCompleteTextView{}`
现在想自定义视图必须继承自这个类而不是TextView了。
这个类位于这个包下
`import android.support.v7.widget.AppCompatAutoCompleteTextView;`
希望楼主能进行下更新
其次特别提醒下其他朋友，使用的时候特别当心，这个不可省略，否则会报错。
[code=html]
xmlns:view="http://schemas.android.com/apk/res-auto"
[/code]

**Comment by RuffianZhong** [comment]
@geekxingyun 
SDK版本不同而已，你导入RTextView应该可以正常使用啊，不会出现报错的。
至于第二点~~那是使用自定义控件最基本的常识~~~~

**Comment by geekxingyun** [comment]
AppCompatAutoCompleteTextView建议更换成这个类，能达到更好的兼容效果，提个小小建议。
主页介绍的XML中建议添加上这个会更加方便，不然初学者很容易踩坑。
`xmlns:view="http://schemas.android.com/apk/res-auto" `

**Comment by RuffianZhong** [comment]
@geekxingyun 
好吧，我以为大家都知道，就直接忽略了
