### ISSUE TITLE
假如我要两种状态都能点击就改变状态该怎么做

### ISSUE THREAD

**Issue by 13787386507** [RuffianZhong/RTextView#11]

**Comment by 13787386507** [comment]
怎么做

**Comment by RuffianZhong** [comment]
@13787386507 
可以描述清楚一点吗？原谅我不是很理解你说的意思

**Comment by 13787386507** [comment]
就是平常状态的那种有两种状态 一个selector true  false 但是都能点击 你这个一个是按压 一个是不可点击的 还有一个是正常的三种状态 我想两种状态切换但是都能点击 没有按压效果

**Comment by RuffianZhong** [comment]
额~~ 我大概猜到你的意思了， 那你就不要设置按下状态的颜色（默认就会是0） 或者你设置按下状态的颜色和默认一样

**Comment by 13787386507** [comment]
我加你qq谈一下或者有什么讨论群

**Comment by RuffianZhong** [comment]
632835821
