### ISSUE TITLE
圆形时能否自适应圆角大小呢

### ISSUE THREAD

**Issue by lxzh** [RuffianZhong/RTextView#12]
针对完全圆形的场景还需要在xml里面写圆角半径，如果用这个控件时是自适应高宽，就无法显示指定圆角大小，需要用java代码显示设置，用起来不够优雅

**Comment by RuffianZhong** [comment]
@ljf1239848066 
有个议论：圆形是在宽高一样时候的才适合，如果宽高不一样要么就是出现类似椭圆的情况，或者是对控件进行裁剪，textView不同于ImageView，个人觉得裁剪不妥当。

对于你说的场景，你可以预先设置 corner_radius 尽可能的大。比如 `rtv:corner_radius="10000dp"` （这样就不用在java代码中设置）
当你控件是宽高一样的时候，一定是一个圆形，不一致时会是类似椭圆的形状

**Comment by lxzh** [comment]
是个问题，不过圆角也可以通过动态生成ShapeDrawable来设置，可能更方便些
