### ISSUE TITLE
控件足够小的时候，文字不能居中

### ISSUE THREAD

**Issue by CoolLiquid** [RuffianZhong/RTextView#13]
<com.ruffian.library.RTextView
            android:id="@+id/relation"
            android:layout_width="45dp"
            android:layout_height="15dp"
            android:gravity="center"
            android:singleLine="true"
            android:textColor="@color/orange_ff9d01"
            android:textSize="@dimen/font_22"
            app:background_normal="@color/yellow_fff6e8"
            app:border_color_normal="@color/orange_ffa71c"
            app:corner_radius="@dimen/dp_10"
            tools:text="asd" />
按照上面这种写法，asd没有居中显示。只有调大height，asd才会慢慢的居中

**Comment by RuffianZhong** [comment]
@weiningpeng 
额~~~要不你把字体调小试试看？
这个问题RTextView表示很冤，控件高度给那么小，字体给那么大，怎么显示的下哦？你换成原生TextView试试看，一样是显示不完全!!!
