### ISSUE TITLE
加个slected状态

### ISSUE THREAD

**Issue by mzdxztm** [RuffianZhong/RTextView#16]
刚开始我挺困惑作者为什么加unable状态，后来想想登陆注册界面，图片选择的确定键等确实可以用。
不过我更希望的是selected，用的比较多，距几个例子

1、列表经常有一些状态性控件，通常拿到json字段之后判断用什么背景和字体色（当然，详情页也有）
2、常用的两张状态控件，收藏、点赞、tab等
3、选择器，底部弹出的少选项选择器，侧边栏搜索条件筛选、图片选择器等
4、列表多选和单选

**Comment by RuffianZhong** [comment]
@mzdxztm 嗯嗯，请关注我的另一个开源库 [RWidgetHelper](https://github.com/RuffianZhong/RWidgetHelper) RWidgetHelper更加完善，功能更加完备，selected状态也有
