### ISSUE TITLE
代码设置RTextView出错

### ISSUE THREAD

**Issue by qiushaopeng** [RuffianZhong/RTextView#2]
使用代码设置RTextView 圆形，运行报错，属性是仿照例子中的xml文件设置的属性。
        RTextView rTextView = new RTextView(context);
        ViewGroup.LayoutParams layoutParams = rTextView.getLayoutParams();
        layoutParams.width = DensityUtils.dp2px(context,100);
        layoutParams.height = DensityUtils.dp2px(context,100);
        rTextView.setLayoutParams(layoutParams);
        rTextView.setGravity(Gravity.CENTER);
        rTextView.setTextColor(textColor);
        rTextView.setBackgroundColorNormal(Color.GRAY);
        rTextView.setCornerRadius(DensityUtils.dp2px(context,50));
        rTextView.setText(“圆形”);
这是什么原因造成的啊？麻烦帮忙看看

**Comment by RuffianZhong** [comment]
@qiushaopeng 
报错原因： ` rTextView.getLayoutParams();` 空指针
分析： `view.getLayoutParams();`  方法的调用必须要有父控件，否则返回的就是null。在这里你直接创建一个RTextView并不存在父控件，所以这里获取到的一定是空，后面设置宽高会出错
解决：使用 new 创建 Params `LinearLayout.LayoutParams layoutParams = new LinearLayout.LayoutParams(ViewGroup.LayoutParams.WRAP_CONTENT, ViewGroup.LayoutParams.WRAP_CONTENT);`

2.之前没有详细测试，用代码生成 RTextView 并且设置相关属性。导致有些属性没有效果，现在已经修复更新至 1.0.3 版本即可
