### ISSUE TITLE
设置了background背景之后，圆角什么都无效了？

### ISSUE THREAD

**Issue by lmdiloveu** [RuffianZhong/RTextView#5]
![image](https://user-images.githubusercontent.com/8290718/37696791-04448444-2d14-11e8-9be5-a29682be7c16.png)

设置背景后，其他设置无效了，背景颜色是修改了，但是圆角什么的没有了！怎么弄

**Comment by RuffianZhong** [comment]
文档首页已经说了，设置系统自带的background会导致圆角这些特性失效，你要使用对应的方法比如：setBackgroundColorNormal ...
