### ISSUE TITLE
icon_src_unable

### ISSUE THREAD

**Issue by qiushui95** [RuffianZhong/RTextView#7]
icon_src_unable这些设置icon的   是不是不能根据icon图片的大小自动展示对应的?必须设置icon_width和height?

**Comment by RuffianZhong** [comment]
@ycx974577817 
现在是这样的，貌似不是很合理，稍后更新版本

**Comment by RuffianZhong** [comment]
@ycx974577817 已经更新 使用最新版本即可

**Comment by qiushui95** [comment]
收到.其实你可以考虑写一个给所有控件设置背景(selector、渐变色、圆角)的工具类

**Comment by RuffianZhong** [comment]
@ycx974577817 知己呀，正在着手做。
后面会给出来，统一封装成helper 提供给各个基础控件使用，项目中也确实有这个需求

**Comment by qiushui95** [comment]
我现在收集的有一个这样的框架,可以给你参考下https://github.com/LiangLuDev/DevShapeUtils
