### ISSUE TITLE
又有建议

### ISSUE THREAD

**Issue by qiushui95** [RuffianZhong/RTextView#8]
我项目里面用的图标很多都是VectorDrawable(矢量图) 在5.0以上可以正常 以下会奔溃,我查资料  发现需要一些适配https://github.com/woxingxiao/VectorCompatTextView

**Comment by RuffianZhong** [comment]
@ycx974577817 632835821加个QQ，说一下怎么出现，我这边试了4.4.2没有发现崩溃

**Comment by qiushui95** [comment]
加了。9745……

**Comment by RuffianZhong** [comment]
@ycx974577817  使用新版本 1.0.8
